Enhance the catch block to work with Java 11.0.7.
Under Java 11.0.7, the call to context.lookup() will throw the following exceptions in some cases:

```
java.lang.IllegalAccessError: class javax.naming.spi.NamingManager (in unnamed module @0xc4ad2a) cannot access class jdk.internal.loader.ClassLoaderValue (in module java.base) because module java.base does not export jdk.internal.loader to unnamed module @0xc4ad2a
	at javax.naming.spi.NamingManager.<clinit>(NamingManager.java:84)
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:332)
	at javax.naming.InitialContext.lookup(InitialContext.java:409)
	at org.jasig.cas.client.configuration.JndiConfigurationStrategyImpl.loadFromContext(JndiConfigurationStrategyImpl.java:78)
	at org.jasig.cas.client.configuration.JndiConfigurationStrategyImpl.get(JndiConfigurationStrategyImpl.java:59)
	at org.jasig.cas.client.configuration.LegacyConfigurationStrategyImpl.get(LegacyConfigurationStrategyImpl.java:53)
	at org.jasig.cas.client.configuration.BaseConfigurationStrategy.getWithCheck(BaseConfigurationStrategy.java:106)
	at org.jasig.cas.client.configuration.BaseConfigurationStrategy.getValue(BaseConfigurationStrategy.java:91)
	at org.jasig.cas.client.configuration.BaseConfigurationStrategy.getString(BaseConfigurationStrategy.java:68)
	at org.jasig.cas.client.util.AbstractConfigurationFilter.getString(AbstractConfigurationFilter.java:60)
	at org.jasig.cas.client.util.AbstractCasFilter.init(AbstractCasFilter.java:70)
```

And:

```
java.lang.NoClassDefFoundError: Could not initialize class javax.naming.spi.NamingManager
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:332)
	at javax.naming.InitialContext.lookup(InitialContext.java:409)
	at org.jasig.cas.client.configuration.JndiConfigurationStrategyImpl.loadFromContext(JndiConfigurationStrategyImpl.java:78)
	at org.jasig.cas.client.configuration.JndiConfigurationStrategyImpl.get(JndiConfigurationStrategyImpl.java:59)
	at org.jasig.cas.client.configuration.LegacyConfigurationStrategyImpl.get(LegacyConfigurationStrategyImpl.java:53)
	at org.jasig.cas.client.configuration.BaseConfigurationStrategy.getWithCheck(BaseConfigurationStrategy.java:106)
	at org.jasig.cas.client.configuration.BaseConfigurationStrategy.getValue(BaseConfigurationStrategy.java:91)
	at org.jasig.cas.client.configuration.BaseConfigurationStrategy.getString(BaseConfigurationStrategy.java:68)
	at org.jasig.cas.client.util.AbstractConfigurationFilter.getString(AbstractConfigurationFilter.java:60)
	at org.jasig.cas.client.util.AbstractCasFilter.init(AbstractCasFilter.java:70)
```

By handling these in the same way that NamingException was already being handled, code running under Java 11.0.7 will continue to work as before.